### ISSUE TITLE
Clicking "About this Site" interferes with history navigation.

### ISSUE THREAD

**Issue by nektro** [aspittel/learn-code-from-us#15]
Clicking on the link to `/about` 3 times requires clicking back 3 times to get back to the home page. This effect does not happen with the link back to `/`.

Observed in: Firefox Nightly 64.0a1 (2018-10-18) (64-bit)

**Comment by aspittel** [comment]
Oh, I bet I have react router set up weirdly -- also, if you type in the url directly, it will 404 in production.

**Comment by VivekNayyar** [comment]
I can take this up.

**Comment by dillon** [comment]
@aspittel [this](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#serving-apps-with-client-side-routing) is why typing in the url directly 404s. In local testing, your computer serves the files to localhost for you, but in production this is not the case. I believe you either need to set up a server or use `hashBrowser` instead of `browserRouter`.

**Comment by aspittel** [comment]
Oh awesome, thank you @dillon and @VivekNayyar!

**Comment by Yurickh** [comment]
#33 and #41 solve the issues described here. Are we able to close this issue out?

**Comment by VivekNayyar** [comment]
@aspiettel I think we can close this issue now since it's fixed from all fronts.

**Comment by aspittel** [comment]
Yes! Thank you!
