### ISSUE TITLE
Smaller/compressed images

### ISSUE THREAD

**Issue by benhalpern** [aspittel/learn-code-from-us#34]
The profile images on the site are currently not optimized, and they could be!! 😄

We use Cloudinary to make this process super simple. There are other alternatives, but definitely worth serving the smallest/most optimized images possible. This includes serving webp versions to chrome users. Cloudinary makes this easy. But there are alternatives. Cloudinary is not the cheapest option at scale.

**Comment by aspittel** [comment]
Oh! It looks like this project may fit into the free plan, thank you so much! Otherwise, I may try something like [this](https://www.npmjs.com/package/compress-images) to do it for free.

**Comment by andrasbacsai** [comment]
What if instead of using `project.Image[0].url`- which is the picture's original size - in the [component](https://github.com/aspittel/learn-code-from-us/blob/master/src/Card/index.js), use `project.Image[0].thumbnails.large.url` which is already a reduced size of the original picture? Not sure if they are optimized, but still better and way smaller in size. (only checked with Chrome's built-in performance audit and all picture related checks are green for that thumbnail.)

**Comment by aspittel** [comment]
Oh woah! @andrasbacsai I didn't know about that! Let's definitely use that.
